site_name: Notes
nav: 
  - Ansible: 
    - Installer: ansible.md
    - Commandes et playbook: ansible_commands.md

  - Python:
    - Créer un environnement virtuel: pip_venv.md

  - RHEL:
    - Commandes à connaitre: commandes_rhel.md
    - Repository: repo.md
    - Firewall: firewall.md
    - Réinitialiser mot de passe root: root_password.md
    - Emergency mode: emergency.md
    - Créer et resize un LVM: create_lvm.md
    - Regex: shell-expansion.md
    - Création de clés privées: ssh_keys.md
    - Crontab: crontab.md
    - Container: container.md
    - SELinux: selinux.md
    - Swap: swap.md
    - NFS: nfs.md
    - Chrony: chrony.md
    - Log: log.md

  - Apache:
    - Configurer apache: apache.md

  - Nagios:
    - Serveur: nagios_server.md
    - Client ncpa: nagios_ncpa.md

  - Git:
    - Commandes git: git_commands.md




theme: readthedocs

